-- Tickets
CREATE TABLE users
(
    id   INTEGER NOT NULL,
    name VARCHAR(30),
    team TEXT,
    role TEXT,
    health DECIMAL NOT NULL DEFAULT 100,
    str DECIMAL NOT NULL DEFAULT 1,
    def DECIMAL NOT NULL DEFAULT 1,
    int DECIMAL NOT NULL DEFAULT 1,
    lvl DECIMAL NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
